# Pirate's Moon qualified compatibility baseline
# DDrawCompat v0.7.1

FullscreenMode = borderless
AltTabFix = keepvidmem(1)
DisplayAspectRatio = 4:3
FpsLimiter = flipstart(30)
ResolutionScale = display(1)
ResolutionScaleFilter = bilinear
SupportedResolutions = 640x480, 1024x768
Antialiasing = msaa4x(0)
TextureFilter = af16x
LogLevel = info
VSync = on
PresentDelay = on(50)
